# Generated by Django 5.0.2 on 2024-02-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('bookno', models.IntegerField(primary_key=True, serialize=False)),
                ('bname', models.CharField(max_length=100)),
                ('bauthor', models.CharField(max_length=100)),
                ('yop', models.DateField()),
                ('aemail', models.EmailField(max_length=254)),
                ('bcat', models.CharField(max_length=100)),
            ],
        ),
    ]
